# Step 4 configuration file - Train/Validation Split

# Root directory of your project (update this to your actual path)
root_dir: "D:/ProjectMach"

# Input directories (from Step 3)
input_step3_train: "D:/ProjectMach/output/output_step_03/train"
input_step3_test: "D:/ProjectMach/output/output_step_03/test"
input_class_distribution: "D:/ProjectMach/output/output_step_03/class_distribution.csv"

# Output directory (for Step 4)
output_step4_dir: "D:/ProjectMach/output/output_step_04"
output_split_assignments: "D:/ProjectMach/output/output_step_04/split_assignments.csv"
